### ISSUE TITLE
Checklist de documentação

### ISSUE THREAD

**Issue by l-ricardo** [UnBParadigmas2024-2/2024.2_G3_Logico_Akinator#6]
- [x] Melhorar a seção "Sobre" com mais detalhes.
- [x] Adicionar gif do projeto finalizado.
- [x] Tornar os manuais de instalação e uso mais detalhados e ilustrados.
- [ ] Criar um vídeo explicativo do projeto de pelo menos 15 minutos.  
- [x] Detalhar as contribuições de cada membro no quadro de participações.  
- [x] Especificar melhor lições aprendidas.
- [x] Descrever as percepções dos membros.
- [x] Especificar melhor as fragilidades.
- [x] Descrever as ideias para porjetos futuros.
- [x] Apresentar ideias mais concretas para melhorias futuras.  
- [x] Referenciar nas fontes não so materiais usados para o projeto, mas tambem os codigos de projetos anteriores usados para inspiração.
